name: Build-and-push-docker

on:
  push:
    branches:
    - 'main'
    - 'dev'
    - 'features/*'

env: 
  BUILD_TAG: ${{ github.run_id }}

jobs:
  build:
    name: Building Dockerfile.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: abhi04d
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        env: 
          IMAGE_NAME: abhi04d/ghactionwhale:${{ env.BUILD_TAG }}
        run: |
          docker build -f ./Dockerfile --no-cache -t ${{ env.IMAGE_NAME }} .
          docker push ${{ env.IMAGE_NAME }}
